/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/spf13/cobra"

	"github.com/karmada-io/karmada/pkg/karmadactl/util"
	pkgutil "github.com/karmada-io/karmada/pkg/util"
)

// hasGroupedSubcommands reports whether any direct child exposes util.TagCommandGroup.
// When true, a grouped index page is useful for navigation (same mechanism as kubectl-style CLIs).
func hasGroupedSubcommands(cmd *cobra.Command) bool {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if g, ok := c.Annotations[util.TagCommandGroup]; ok && strings.TrimSpace(g) != "" {
			return true
		}
	}
	return false
}

func defaultCommandGroupOrder() []string {
	return []string{
		util.GroupBasic,
		util.GroupClusterRegistration,
		util.GroupClusterManagement,
		util.GroupClusterTroubleshootingAndDebugging,
		util.GroupAdvancedCommands,
		util.GroupSettingsCommands,
		util.GroupOtherCommands,
	}
}

func indexPageTitle(root *cobra.Command) string {
	cp := strings.TrimSpace(root.CommandPath())
	if cp == "" {
		return "Commands"
	}
	r := []rune(cp)
	r[0] = unicode.ToUpper(r[0])
	return string(r) + " Commands"
}

func printCLIByTag(cmd *cobra.Command, all []*cobra.Command, tag string) string {
	var result strings.Builder
	var pl []string
	for _, c := range all {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if val, ok := c.Annotations[util.TagCommandGroup]; !ok || val != tag {
			continue
		}
		cname := cmd.Name() + " " + c.Name()
		link := strings.ReplaceAll(cname, " ", "_") + ".md"
		pl = append(pl, fmt.Sprintf("* [%s](%s)\t - %s\n", cname, link, c.Long))
	}

	for _, v := range pl {
		result.WriteString(v)
	}
	result.WriteString("\n")
	return result.String()
}

// tryGenGroupedCommandIndex writes "<commandPath>_index.md" when subcommands use util.TagCommandGroup.
// It is a no-op (returns nil) when no such annotations exist — no karmadactl-specific branching required.
func tryGenGroupedCommandIndex(root *cobra.Command, dir string) error {
	if !hasGroupedSubcommands(root) {
		return nil
	}

	basename := strings.ReplaceAll(root.CommandPath(), " ", "_") + "_index.md"
	filename := filepath.Join(dir, basename)
	f, err := os.OpenFile(filename, os.O_CREATE|os.O_RDWR|os.O_TRUNC, pkgutil.DefaultFilePerm)
	if err != nil {
		return err
	}
	defer f.Close()

	title := indexPageTitle(root)
	if _, err = io.WriteString(f, "---\ntitle: "+title+"\n---\n\n\n"); err != nil {
		return err
	}

	for _, tp := range defaultCommandGroupOrder() {
		if _, err = io.WriteString(f, "## "+tp+"\n\n"); err != nil {
			return err
		}
		str := printCLIByTag(root, root.Commands(), tp)
		if _, err = io.WriteString(f, str); err != nil {
			return err
		}
	}

	_, err = io.WriteString(f, "###### Auto generated by [script in Karmada]("+genFlagDocsRepoPath+").")
	return err
}
